#!/usr/bin/env bash
# Lints the codebase.
# Dependencies:
# - poetry install --only lint
# Usage:
# $ ./lint .

if [ $# -eq 0 ]; then
  echo "Usage: $0 TARGET_PATHS"
  exit 1
fi

# Args
TARGET_PATHS="$@"

errors=0

echo "Linting paths: $TARGET_PATHS ..."
echo "Linting with toml-sort (checks pyproject.toml formatting) ..."
poetry run toml-sort \
  --no-sort-tables \
  --trailing-comma-inline-array \
  --spaces-indent-inline-array 4 \
  --check pyproject.toml || ((errors++))

# https://beta.ruff.rs/docs/
echo "Linting with ruff (isort / flake8 / autoflake issues) ..."
poetry run ruff check $TARGET_PATHS || ((errors++))

echo "Linting with mypy (type checking) ..."
poetry run mypy --exclude .venv $TARGET_PATHS || ((errors++))

if [[ $errors -gt 0 ]]; then
  echo "🚨 $errors linters found errors!"
  exit $errors
fi

echo "✅ Success!"
