# CI/CD workflow for the project.
name: cicd
on:
  push:

jobs:
  # Check for linting errors.
  lint:
    uses: ./.github/workflows/python-make-target.yaml
    with:
      target: lint

  # Run the test suite.
  test:
    uses: ./.github/workflows/python-make-target.yaml
    with:
      target: test
